### PR TITLE
Voice main clean up

### PR DESCRIPTION
**Pull request by akhil-ghatiki**
@FultonBrowne  This code can be written in much cleaner way. Use Lists to add headers to the audio format. Iterate over lists and add it to the output stream.
Good luck !

### CODE REVIEW

**Comment by FultonBrowne** [comment]
@akhil-ghatiki, have you tested the code?

**Comment by akhil-ghatiki** [comment]
> @akhil-ghatiki, have you tested the code?

There are no test suites. The quality test was failing because of file name. I  have renamed and push the changes again.

**Comment by akhil-ghatiki** [comment]
@FultonBrowne  Please let me know if there is any problem with merging this PR.

**Comment by FultonBrowne** [comment]
thank you @akhil-ghatiki  for contributing, I am doing some research on where and how I should market ara, so how did you find ara?

**Pull request merged**
